# Auto-generated by Hyperbee - Meeting Assistant Bot

import json

def format_user_data(raw_data):
    return json.dumps([
        {
            "id": user.get("id"),
            "name": f"{user.get('first_name', '')} {user.get('last_name', '')}".strip(),
            "email": user.get("email"),
            "role": user.get("role", "N/A"),
        }
        for user in raw_data
    ], indent=4)

# Example usage
sample_data = [
    {"id": 1, "first_name": "Alice", "last_name": "Johnson", "email": "alice@example.com", "role": "Engineer"},
    {"id": 2, "first_name": "Bob", "last_name": "", "email": "bob@example.com"}, 
]

print(format_user_data(sample_data))
